<?php

$server = new Zend_Json_Server();
//$server->setClass('');
$smd = $server->getServiceMap();

header("Content-Type: text/html; charset=UTF-8");
echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";

?><?=$this->doctype('XHTML1_TRANSITIONAL')?>
<html xml:lang="en-US" lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta name="" content="<?=$this->escape($this->title)?>" />
	<meta name="keywords" content="<?=$this->escape(implode(',', array_merge(array(
		'',
	), (array)$this->keywords)))?>" />
	<meta name="description" content="<?=$this->escape($this->description)?>" />
    <?php
        $this->headScript()
            ->appendFile('/js/3rd_party/ckeditor/ckeditor.js')
            ->appendFile('/js/3rd_party/ckeditor/adapters/jquery.js');
    ?>

    <?=$this->headLink()?>
    <?=$this->headScript()?>



	<title>Traxpacking - Backpacking by GPS</title>
</head>
<body>
    <?php
        /*$authUrl = array(
            'module' => 'default',
            'controller' => 'auth',
            'action' => 'logout',
        );

        if(Zend_Auth::getInstance()->hasIdentity()) {
            echo '<span><a href="' . $this->url($authUrl, null, true) . '">logout</a></span>';
        } else {
            $authUrl['action'] = 'login';
            echo '<span><a href="' . $this->url($authUrl, null, true) . '">login</a></span>';
        }*/
    ?>
    <h1>Welcome to TraxPacking</h1>
    <div id="topnav">
        <?= $this->navigation()->menu(); ?>
        <div class="clear"></div>
    </div>


	<?php
        $view = Zend_Controller_Front::getInstance()->getParam("bootstrap")->getResource("view");
    ?>
    <div id="content">
        <?php
            $msgProvider = new Tp_Provider_FlashMessage();
            echo $msgProvider->provideMessages();
        ?>
        <?= $this->layout()->content; ?>
        <div class="clear"></div>
    </div>

    <div id="footer">
        <div id="credentials">
            <?php
            $user = Zend_Auth::getInstance()->getStorage()->read();
            $username  = ($user === null) ? 'guest' : $user->email . " ({$user->role})";
            echo 'User: ' . $username;
            ?>
        </div>
        <div id="breadcrumbs">
            Breadcrumbs: <?= $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(true)->setSeparator(" : "); ?>
        </div>
        <div id="popupForm"></div>
    </div>
    <?php
        $msgProvider = new Tp_Provider_FlashMessage();
        echo $msgProvider->provideDebugMessages();
    ?>
</body>
</html>
