<ul>
<?php

$html = array();

foreach ($this->container as $page) {?>
	<li>
		<?=$this->menu()->htmlify($page) . PHP_EOL;?><?php
		if ($page->pages) {
		
			//Zend_Debug::dump($page->getClass());exit;
			?>
			<ul class="<?=$page->getClass()?>"><?php
			foreach ($page->pages as $subpage)  {?>
				<li>
					<a href="<?=$subpage->getHref()?>">
						<?=$subpage->getLabel()?>
					</a>
				</li><?php
			}?>
			</ul><?php
		}?>
	</li><?php
}?>
</ul>