<?php
    $this->javascript("SVG.createSvgWorldMap(
        function() {
            C.log('fetching all countries with Pictures....');
            rpc.setAsyncSuccess(function(response) {
                SVG.setupSvgWorldMap(response);
                SVG.drawPois(" . $this->jsonPoiArray . ");
            });
            rpc.getCountriesWithPictures();

        }
    );");
?>


<div id="svgMapContainer" class="worldMapLarge">
</div>
