<?php
    $ifPhoto = "";
    if($this->type == "photo") {
        $ifPhoto = "PHOTO.preparePhotoMap();";
    }

    $this->javascript("SVG.createSvgWorldMap(
        function() {
            C.log('fetching all countries with Pictures....');
            rpc.setAsyncSuccess(function(response) {
                SVG.setupSvgWorldMap(response);
                " . $ifPhoto . "
                SVG.drawPois(" . $this->jsonPoiArray . ", '" . $this->type . "');
            });
            rpc.getCountriesWithPictures();
        }
    );");
?>


<div id="svgMapContainer" class="worldMapLarge">
</div>
