<?php
    if($this->poi == null) {
        echo '<h2>There are no photos yet!</h2>';
    } else {
?>
    <?php
        if($this->poi->pictures->count() > 0) {
    ?>

            <div id="tpScrollHorizontal" class="jThumbnailScroller">
                <div class="jTscrollerContainer">
                    <div class="jTscroller">
                        <?php
                            //$this->poi->pictures
                            foreach($this->poi->getPicturesOrderedByDate() as $p) {
                                $small = "/media/" . $p->filename . "_small.jpg";
                                $large = "/media/" . $p->filename . "_medium.jpg";

                        ?>
                                <a
                                   class="lightview"
                                   data-lightview-group="poiPictures"
                                   data-lightview-options="onHide: WHYJUSTIFY.toggleFullscreen, position:top, controls: { type: 'relative', slider: { items: 10 } }, skin: 'dark'"
                                   data-lightview-caption="<?= nl2br($p->description) ?>"
                                   href="<?= $large ?>"
                                >
                                      <img src="<?= $small ?>" alt="" />
                                </a>
                        <?php
                            }
                        ?>

                    </div>
                </div>
                <a href="#" class="jTscrollerPrevButton"></a>
                <a href="#" class="jTscrollerNextButton"></a>
            </div>

<?php
            $this->javascript('
            $(window).load(function() {
                $("#tpScrollHorizontal").thumbnailScroller({
                    scrollerType:"clickButtons",
                    scrollerOrientation:"horizontal",
                    scrollSpeed:2,
                    scrollEasing:"easeOutCirc",
                    scrollEasingAmount:800,
                    acceleration:4,
                    scrollSpeed:800,
                    noScrollCenterSpace:10,
                    autoScrolling:1,
                    autoScrollingSpeed:3000,
                    autoScrollingEasing:"easeInOutQuad",
                    autoScrollingDelay:500
                });

                $("#tpScroll a.lightview").bind("click", function() {
                    WHYJUSTIFY.toggleFullscreen();
                });
            });', false);

        }
    }
?>