<?php
    $imgArray = array();
    $msgArray = array();
    foreach($this->pictures as $p) {
        $imgArray[] = "/media/" . $p->filename . "_medium.jpg";
        $msgArray[] = "<h1>" . $p->poi->title . "</h1><p>" . $p->description . "</p>";
    }
    $this->javascript('
        $("#playground").css("padding", 0);
        $("body").addClass("photo-fullscreen", 0);
        var msgArray = ' . Zend_Json::encode($msgArray) . ',
        pMsg = $(".photo-fullscreen .photo-message");

        pMsg.html("<div>" + msgArray[0] + "</div>");

        $.mbBgndGallery.buildGallery({
	        containment:"body", // or "#myGalleryElement"
	        timer:4000,
	        effTimer:1000,
	        controls:"#gallery_controls",
	        grayScale:false,
            effect:"fade",
            appendNewMessage: function(pMsg, newIndex) {
                C.log("append Message with Index: ", newIndex, msgArray[newIndex]);
                if($("div", pMsg).length === 0) {
                    pMsg.append("<div>" + msgArray[newIndex] + "</div>");
                    $("div", pMsg).fadeIn(900);
                }
            },

            onChange: function(opt) {
                pMsg = $(".photo-fullscreen .photo-message");
                C.log(parseInt(opt.imageCounter, 10));
                var index = parseInt(opt.imageCounter, 10),
                    thisthis = this,
                    obsoleteEntry = $("div", pMsg);
                    C.log("obsolete entry", obsoleteEntry);
                
                
                /*if(obsoleteEntry.length <= 0) {
                    thisthis.appendNewMessage(pMsg, index);
                }

                if(obsoleteEntry.length > 1) {
                    pMsg.empty();    
                }*/

                obsoleteEntry.fadeOut(900, function() {
                    $(this).remove();
                    thisthis.appendNewMessage(pMsg, index);
                });
  
                
            },
            onFullscreen: function(opt) {
                C.log("huston, we are fullscreen");
                pMsg = $(".photo-fullscreen .photo-message");
                // loesche allen inhalt der moeglicherweise vorhanden
                

                pMsgFull = pMsg.addClass("photo-message-fullscreen");
                pMsg.remove();
                $(".mbBgndGallery").append(pMsgFull);
                
                pMsgFull.empty();
                this.appendNewMessage(pMsg, opt.imageCounter);
                
            },
            onExitFullscreen: function(opt) {
                C.log(opt.imageCounter);
C.log("huston, all engines are back to normal (no fullscreen)");
                pMsg = $(".photo-fullscreen .photo-message");
                pMsg.remove();
                pMsg.empty();
                pMsg.removeClass("photo-message-fullscreen");
                $(".photo-fullscreen").append(pMsg);
                this.appendNewMessage(pMsg, opt.imageCounter);
                
            },
	        images:' . Zend_Json::encode($imgArray) . '
        });

        


    ');

    if($this->pictures == null || empty($this->pictures)) {
        echo '<h2>There are no photos yet!</h2>';
    } else  {
?>
        
                <div id="gallery_controls">
	                <div class="pause">pause</div>
	                <div class="play">play</div>
	                <div class="prev">prev</div>
	                <div class="next">next</div>
	                <div class="counter"></div>
                    <div class="fullscreen">fullscreen</div>
                </div>
                <div class="photo-message"><div>
        
        
<?php
    }

?>
