<?php
    if($this->poi == null) {
        echo '<h2>Kein POI mit URL: ' . $this->url . '</h2>';
    } else {
?>
    <div id="svgMapContainer_<?= $this->poi->id ?>" class="worldMapSmall">
    </div>
    <div id="tpScroll" class="jThumbnailScroller" style="height:300px;  ">
        <div class="jTscrollerContainer">
            <div class="jTscroller">
                <?php
                    foreach($this->poi->pictures as $p) {
                        $small = "/media/" . $p->filename . "_small.jpg";
                        $large = "/media/" . $p->filename . "_medium.jpg";

                ?>
                        <a
                           class="lightview"
                           data-lightview-group="poiPictures"
                           data-lightview-options="onHide: WHYJUSTIFY.toggleFullscreen, position:top, controls: { type: 'relative', slider: { items: 10 } }, skin: 'dark'"
                           data-lightview-caption="<?= $p->description ?>"
                           href="<?= $large ?>"
                        >
                              <img src="<?= $small ?>" alt="" />
                        </a>
                <?php
                    }
                ?>

            </div>
        </div>
        <a href="#" class="jTscrollerPrevButton"></a>
        <a href="#" class="jTscrollerNextButton"></a>
    </div>

<?php
            $this->javascript('
            $(window).load(function() {
                $("#tpScroll").thumbnailScroller({
                    scrollerType:"clickButtons",
                    scrollerOrientation:"vertical",
                    scrollSpeed:2,
                    scrollEasing:"easeOutCirc",
                    scrollEasingAmount:800,
                    acceleration:4,
                    scrollSpeed:800,
                    noScrollCenterSpace:10,
                    autoScrolling:1,
                    autoScrollingSpeed:3000,
                    autoScrollingEasing:"easeInOutQuad",
                    autoScrollingDelay:500
                });

                $("#tpScroll a.lightview").bind("click", function() {
                    WHYJUSTIFY.toggleFullscreen();
                });



            });
        ', false);

        $this->javascript("
            var tmpRpc = jQuery.Zend.jsonrpc({ url : '/ajax/rpc.php', async : true});
            SVG.createSvgWorldMap(
                function() {
                    tmpRpc.setAsyncSuccess(function(response) {
                        SVG.setupSvgWorldMap([{ name : '" . $this->poi->country->name . "'}], 'svgMapContainer_" . $this->poi->id . "');
                        SVG.drawPois(" . $this->poi->getPoisAsJsonArray() . ", 'svgMapContainer_" . $this->poi->id . "');
                    });
                    tmpRpc.getCountryMap();
                }, 'svgMapContainer_" . $this->poi->id . "'
            );
        ");
    }
?>