<div id="tpScroll" class="jThumbnailScroller" style="height:300px;  ">
    <div class="jTscrollerContainer">
        <div class="jTscroller">
            <?php
                foreach($this->poi->pictures as $p) {
                    $small = "/media/" . $p->filename . "_small.jpg";
                    $large = "/media/" . $p->filename . "_medium.jpg";

            ?>
                    <a href="<?= $large ?>"><img src="<?= $small ?>" alt="" title="<?= $p->description ?>"/></a>
            <?php
                }
            ?>

        </div>
    </div>
    <a href="#" class="jTscrollerPrevButton"></a>
    <a href="#" class="jTscrollerNextButton"></a>
</div>

<?php
        $this->javascript('
        $("#tpScroll").thumbnailScroller({
            scrollerType:"clickButtons",
            scrollerOrientation:"vertical",
            scrollSpeed:2,
            scrollEasing:"easeOutCirc",
            scrollEasingAmount:800,
            acceleration:4,
            scrollSpeed:800,
            noScrollCenterSpace:10,
            autoScrolling:1,
            autoScrollingSpeed:3000,
            autoScrollingEasing:"easeInOutQuad",
            autoScrollingDelay:500
        });

        var theWrap = \'\';

        $("#tS3 img").imgZoom({
            rotate : 1,
            wrap : $("#wrapMarkup").html()
        });
    ');
?>

<div id="wrapMarkup" style="display:none">
    <div class="imgzoom-wrap imgzoom-width">
        <div class="imgzoom-container imgzoom-width imgzoom-height">
            <a href="#" class="imgzoom-prev"><span>Prev</span></a>
            <a href="#" class="imgzoom-next"><span>Next</span></a>
        </div>
        <div class="imgzoom-counter">
            <span class="imgzoom-current" />&nbsp;of&nbsp;
            <span class="imgzoom-last" />
        </div>
        <div class="imgzoom-title" />
        <div class="imgzoom-close">----------Close</div>
    </div>
</div>

