<?php

$server = new Zend_Json_Server();
//$server->setClass('');
$smd = $server->getServiceMap();

?><?=$this->doctype()?>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="" content="<?=$this->escape($this->title)?>">
	<meta name="keywords" content="<?=$this->escape(implode(',', array_merge(array(
		'',
	), (array)$this->keywords)))?>">
	<meta name="description" content="<?=$this->escape($this->description)?>">
	<?=$this->headLink()->appendStylesheet($this->baseUrl() . '/css/main.css')?>
	<?=$this->headStyle()?>
	<?=$this->layout()->css?>
	<?php
	echo $this->jQuery()
		->setVersion('1.7.1')->enable()
		->setUiVersion('1.8')->uiEnable()
		->addStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/smoothness/jquery-ui.css');
	?>
	<script>const BASE_URL = <?=json_encode($this->baseUrl())?>;</script>
	<?=$this->headScript()->appendFile('/js/jquery.zend.jsonrpc.js')->appendFile('/js/json2.js')->appendFile('/js/site.js')?>
	<script>
		var rpc;
		$(document).ready(function() {
			rpc = jQuery.Zend.jsonrpc({
				url : <?=json_encode($this->baseUrl('/ajax'))?>
				, smd : <?=$smd?>
				, async : true
			});
		});</script>
	<?=$this->layout()->headJavascript?>
	<title>Traxpacking - Backpacking by GPS</title>
</head>
<body>
    <?php
        /*$authUrl = array(
            'module' => 'default',
            'controller' => 'auth',
            'action' => 'logout',
        );

        if(Zend_Auth::getInstance()->hasIdentity()) {
            echo '<span><a href="' . $this->url($authUrl, null, true) . '">logout</a></span>';
        } else {
            $authUrl['action'] = 'login';
            echo '<span><a href="' . $this->url($authUrl, null, true) . '">login</a></span>';
        }*/
    ?>
    <h1>Welcome to TraxPacking</h1>
    <div id="topnav">
        <?= $this->navigation()->menu(); ?>
        <div class="clear"></div>
    </div>


	<?php
        $view = Zend_Controller_Front::getInstance()->getParam("bootstrap")->getResource("view");
        $messages = array();

        $msgProvider = new Tp_Provider_FlashMessage();
        echo $msgProvider->provideMessages();
    ?>
    <div id="content">
        <?= $this->layout()->content; ?>
        <div class="clear"></div>
    </div>

    <div id="footer">
        <div id="credentials">
            <?php
            $user = Zend_Auth::getInstance()->getStorage()->read();
            $username  = ($user === null) ? 'guest' : $user->email . " ({$user->role})";
            echo 'User: ' . $username;
            ?>
        </div>
        <div id="breadcrumbs">
            Breadcrumbs: <?= $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(true)->setSeparator(" : "); ?>
        </div>
    </div>
</body>
</html>
